trailingComma: "es5"
singleQuote: true
semi: false
tabWidth: 2
overrides:
  - files:
    - ".js"
    - ".ts"
    options:
      semi: true
      singleQuote: true
  - files:
      - "*.html"
    options:
      tabWidth: 2
